# Generated by Django 3.2.4 on 2024-06-04 11:52

import django.core.validators
from django.db import migrations, models

import app.core.models.article_block


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articleblock",
            name="background_text",
            field=models.CharField(
                max_length=100, null=True, verbose_name="background text"
            ),
        ),
        migrations.AlterField(
            model_name="articleblock",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="avatar",
                null=True,
                upload_to=app.core.models.article_block.ArticleBlock.image_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    )
                ],
                verbose_name="avatar",
            ),
        ),
        migrations.AlterField(
            model_name="articleblock",
            name="text",
            field=models.TextField(null=True, verbose_name="text"),
        ),
        migrations.AlterField(
            model_name="articleblock",
            name="text_tag",
            field=models.CharField(
                max_length=50, null=True, verbose_name="text position"
            ),
        ),
        migrations.AlterField(
            model_name="articleblock",
            name="video_url",
            field=models.TextField(null=True, verbose_name="video url"),
        ),
    ]
