# Generated by Django 3.2.4 on 2024-06-01 14:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
